### ISSUE TITLE
hbase start - java.io.FileNotFoundException: /home/vagrant/hbase/logs/SecurityAuth.audit (Permission denied) hdp-node-03: 	at java.io.FileOutputStream.open(Native Method)

### ISSUE THREAD

**Issue by gitava** [gitava/Big-Data-Study#32]
start w/o sudo
```
[vagrant@hdp-node-01 ~/hbase]$~/hbase/bin/start-hbase.sh
```

```
hdp-node-03: java.io.FileNotFoundException: /home/vagrant/hbase/logs/SecurityAuth.audit (Permission denied)
hdp-node-03: 	at java.io.FileOutputStream.open(Native Method)
hdp-node-03: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
hdp-node-03: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:142)
hdp-node-03: 	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
hdp-node-03: 	at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:207)
hdp-node-03: 	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
hdp-node-03: 	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
hdp-node-03: 	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
hdp-node-02: log4j:ERROR setFile(null,true) call failed.
hdp-node-02: java.io.FileNotFoundException: /home/vagrant/hbase/logs/SecurityAuth.audit (Permission denied)
hdp-node-02: 	at java.io.FileOutputStream.open(Native Method)
hdp-node-02: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
hdp-node-02: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:142)
hdp-node-02: 	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
hdp-node-02: 	at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:207)
hdp-node-02: 	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
hdp-node-02: 	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
hdp-node-02: 	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
hdp-node-01: log4j:ERROR setFile(null,true) call failed.
hdp-node-01: java.io.FileNotFoundException: /home/vagrant/hbase/logs/SecurityAuth.audit (Permission denied)
hdp-node-01: 	at java.io.FileOutputStream.open(Native Method)
hdp-node-01: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
hdp-node-01: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:142)
hdp-node-01: 	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
hdp-node-01: 	at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:207)
hdp-node-01: 	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
hdp-node-01: 	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
hdp-node-01: 	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)

```

**Comment by gitava** [comment]
```
[vagrant@hdp-node-01 ~/hbase/logs]$ls -ltr
total 352
-rw-r--r--. 1 root    vagrant   1314 Jul  3 02:44 hbase-root-master-hdp-node-01.out.1
-rw-r--r--. 1 root    vagrant      0 Jul  3 02:45 hbase-root-zookeeper-hdp-node-01.out
-rw-r--r--. 1 root    vagrant      0 Jul  3 02:45 hbase-root-regionserver-hdp-node-01.out
-rw-r--r--. 1 root    vagrant  31096 Jul  3 02:46 hbase-root-regionserver-hdp-node-01.log
-rw-r--r--. 1 root    vagrant   1315 Jul  3 02:49 hbase-root-master-hdp-node-01.out
-rw-r--r--. 1 root    vagrant   2675 Jul  3 02:49 SecurityAuth.audit
-rw-r--r--. 1 root    vagrant 180688 Jul  3 02:49 hbase-root-master-hdp-node-01.log
-rw-r--r--. 1 root    vagrant  10680 Jul  3 02:49 hbase-root-zookeeper-hdp-node-01.log
-rw-rw-r--. 1 vagrant vagrant    753 Jul  3 02:49 hbase-vagrant-zookeeper-hdp-node-01.log
-rw-rw-r--. 1 vagrant vagrant   3126 Jul  3 02:49 hbase-vagrant-zookeeper-hdp-node-01.out
-rw-rw-r--. 1 vagrant vagrant   2539 Jul  3 02:49 hbase-vagrant-master-hdp-node-01.out
-rw-rw-r--. 1 vagrant vagrant   2539 Jul  3 02:50 hbase-vagrant-regionserver-hdp-node-01.out
-rw-rw-r--. 1 vagrant vagrant  46752 Jul  3 02:50 hbase-vagrant-master-hdp-node-01.log
-rw-rw-r--. 1 vagrant vagrant  51904 Jul  3 02:50 hbase-vagrant-regionserver-hdp-node-01.log
[vagrant@hdp-node-01 ~/hbase/logs]$chown vagrant:vagrant *
chown: changing ownership of 'hbase-root-master-hdp-node-01.log': Permission denied
chown: changing ownership of 'hbase-root-master-hdp-node-01.out': Permission denied
chown: changing ownership of 'hbase-root-master-hdp-node-01.out.1': Permission denied
chown: changing ownership of 'hbase-root-regionserver-hdp-node-01.log': Permission denied
chown: changing ownership of 'hbase-root-regionserver-hdp-node-01.out': Permission denied
chown: changing ownership of 'hbase-root-zookeeper-hdp-node-01.log': Permission denied
chown: changing ownership of 'hbase-root-zookeeper-hdp-node-01.out': Permission denied
chown: changing ownership of 'SecurityAuth.audit': Permission denied
[vagrant@hdp-node-01 ~/hbase/logs]$sudo chown vagrant:vagrant *
[vagrant@hdp-node-01 ~/hbase/logs]$ll
total 504
-rw-r--r--. 1 vagrant vagrant   2675 Jul  3 02:49 SecurityAuth.audit
-rw-r--r--. 1 vagrant vagrant 180688 Jul  3 02:49 hbase-root-master-hdp-node-01.log
-rw-r--r--. 1 vagrant vagrant   1315 Jul  3 02:49 hbase-root-master-hdp-node-01.out
-rw-r--r--. 1 vagrant vagrant   1314 Jul  3 02:44 hbase-root-master-hdp-node-01.out.1
-rw-r--r--. 1 vagrant vagrant  31096 Jul  3 02:46 hbase-root-regionserver-hdp-node-01.log
-rw-r--r--. 1 vagrant vagrant      0 Jul  3 02:45 hbase-root-regionserver-hdp-node-01.out
-rw-r--r--. 1 vagrant vagrant  10680 Jul  3 02:49 hbase-root-zookeeper-hdp-node-01.log
-rw-r--r--. 1 vagrant vagrant      0 Jul  3 02:45 hbase-root-zookeeper-hdp-node-01.out
-rw-rw-r--. 1 vagrant vagrant  46752 Jul  3 02:50 hbase-vagrant-master-hdp-node-01.log
-rw-rw-r--. 1 vagrant vagrant   2539 Jul  3 02:49 hbase-vagrant-master-hdp-node-01.out
-rw-rw-r--. 1 vagrant vagrant 207481 Jul  3 02:51 hbase-vagrant-regionserver-hdp-node-01.log
-rw-rw-r--. 1 vagrant vagrant   2539 Jul  3 02:50 hbase-vagrant-regionserver-hdp-node-01.out
-rw-rw-r--. 1 vagrant vagrant    753 Jul  3 02:49 hbase-vagrant-zookeeper-hdp-node-01.log
-rw-rw-r--. 1 vagrant vagrant   3126 Jul  3 02:49 hbase-vagrant-zookeeper-hdp-node-01.out
[vagrant@hdp-node-01 ~/hbase/logs]$
```

**Comment by gitava** [comment]
made above change on 3 servers.

**Comment by gitava** [comment]
```
[vagrant@hdp-node-01 ~/hbase/logs]$~/hbase/bin/start-hbase.sh
hdp-node-03: running zookeeper, logging to /home/vagrant/hbase/logs/hbase-vagrant-zookeeper-hdp-node-03.out
hdp-node-02: running zookeeper, logging to /home/vagrant/hbase/logs/hbase-vagrant-zookeeper-hdp-node-02.out
hdp-node-01: running zookeeper, logging to /home/vagrant/hbase/logs/hbase-vagrant-zookeeper-hdp-node-01.out
running master, logging to /home/vagrant/hbase/logs/hbase-vagrant-master-hdp-node-01.out
hdp-node-02: running regionserver, logging to /home/vagrant/hbase/logs/hbase-vagrant-regionserver-hdp-node-02.out
hdp-node-03: running regionserver, logging to /home/vagrant/hbase/logs/hbase-vagrant-regionserver-hdp-node-03.out
hdp-node-01: running regionserver, logging to /home/vagrant/hbase/logs/hbase-vagrant-regionserver-hdp-node-01.out
```

**Comment by gitava** [comment]
OK now.
