### ISSUE TITLE
Pig installation - Exception in thread "main" java.lang.NoClassDefFoundError: org/joda/time/ReadableInstant

### ISSUE THREAD

**Issue by gitava** [gitava/Big-Data-Study#5]
```bash
[vagrant@hdp-node-01 ~]$ pig
Exception in thread "main" java.lang.NoClassDefFoundError: org/joda/time/ReadableInstant
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:237)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:158)
Caused by: java.lang.ClassNotFoundException: org.joda.time.ReadableInstant
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 4 more
```

**Comment by gitava** [comment]
as per https://stackoverflow.com/questions/24781932/hadoop-cant-find-joda-dependency

> Copied the joda-time.jar to a hadoop common library. Probably not the best solution, but at least it works.

**Comment by gitava** [comment]
copy the following files from /home/vagrant/pig/lib to /home/vagrant/hadoop/share/hadoop/common

* joda-time-2.9.3.jar
* jline-2.11.jar
* antlr-runtime-3.4.jar



```bash
[vagrant@hdp-node-01 common]$ sudo chown 501:joda-time-2.9.3.jar
[vagrant@hdp-node-01 common]$ sudo chown 501:dialout jline-2.11.jar
[vagrant@hdp-node-01 common]$ sudo chown 501:dialout antlr-runtime-3.4.jar
```

```bash
[vagrant@hdp-node-01 common]$ pwd
/home/vagrant/hadoop/share/hadoop/common
[vagrant@hdp-node-01 common]$ ls -l
total 7556
-rw-r--r--. 1 501 dialout  164368 Jun 26 11:37 antlr-runtime-3.4.jar
-rw-r--r--. 1 501 dialout 2619447 Nov 13  2018 hadoop-common-2.9.2-tests.jar
-rw-r--r--. 1 501 dialout 3906902 Nov 13  2018 hadoop-common-2.9.2.jar
-rw-r--r--. 1 501 dialout  188721 Nov 13  2018 hadoop-nfs-2.9.2.jar
drwxr-xr-x. 2 501 dialout    4096 Nov 13  2018 jdiff
-rw-r--r--. 1 501 dialout  208781 Jun 26 11:36 jline-2.11.jar
-rw-r--r--. 1 501 dialout  627814 Jun 26 11:36 joda-time-2.9.3.jar
drwxr-xr-x. 2 501 dialout    4096 Nov 13  2018 lib
drwxr-xr-x. 2 501 dialout      89 Nov 13  2018 sources
drwxr-xr-x. 2 501 dialout      27 Nov 13  2018 templates
[vagrant@hdp-node-01 common]$
```

**Comment by gitava** [comment]
Grunt shell is working.

```bash
[vagrant@hdp-node-01 common]$ pig
20/06/26 11:43:30 INFO pig.ExecTypeProvider: Trying ExecType : LOCAL
20/06/26 11:43:30 INFO pig.ExecTypeProvider: Trying ExecType : MAPREDUCE
20/06/26 11:43:30 INFO pig.ExecTypeProvider: Picked MAPREDUCE as the ExecType
20/06/26 11:43:30 WARN pig.Main: Cannot write to log file: /home/vagrant/hadoop/share/hadoop/common/pig_1593171810130.log
2020-06-26 11:43:30,131 [main] INFO  org.apache.pig.Main - Apache Pig version 0.17.0 (r1797386) compiled Jun 02 2017, 15:41:58
2020-06-26 11:43:30,165 [main] INFO  org.apache.pig.impl.util.Utils - Default bootup file /home/vagrant/.pigbootup not found
2020-06-26 11:43:30,736 [main] INFO  org.apache.hadoop.conf.Configuration.deprecation - mapred.job.tracker is deprecated. Instead, use mapreduce.jobtracker.address
2020-06-26 11:43:30,736 [main] INFO  org.apache.pig.backend.hadoop.executionengine.HExecutionEngine - Connecting to hadoop file system at: hdfs://hdp-node-01:9000
2020-06-26 11:43:31,517 [main] INFO  org.apache.pig.PigServer - Pig Script ID for the session: PIG-default-d0522833-2f02-4f7e-96d1-ed09934b15ef
2020-06-26 11:43:31,517 [main] WARN  org.apache.pig.PigServer - ATS is disabled since yarn.timeline-service.enabled set to false
grunt>

```

**Comment by gitava** [comment]
Find a better fix which doesn't need the jar file to be moved.

Change the configuration file: /home/vagrant/hadoop/etc/hadoop/

```shell
# Add customized classpath in order to run own java code
#export HADOOP_CLASSPATH=/home/vagrant/myclass

# Add to solve pig/hive class lib issues.
export HADOOP_CLASSPATH=$HADOOP_CLASSPATH:/home/vagrant/myclass
```

it's now working .
